services:  

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    networks:
      - todo-network

  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "80:80"
    networks:
      - todo-network

networks:
  todo-network: 
    driver: bridge
